spring.application.name=movies

#JPA
spring.jpa.show-sql=true

# H2
spring.datasource.url=jdbc:h2:mem:testdb

# h2 consolen asetukset
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# DEBUG
logging.level.org.springframework.web=DEBUG

# DATA REST PATH
# spring.data.rest.basePath=/api